### ISSUE TITLE
Gas use optimization - removing `ownerToNFTokenCount`

### ISSUE THREAD

**Issue by mg6maciej** [0xcert/ethereum-erc721#114] opened 2018-06-25 09:28 UTC
If you move implementation of `tokenOfOwnerByIndex` and related fields (`ownerToIds` and `idToOwnerIndex`) to `NFToken`, you can remove `ownerToNFTokenCount` and use `ownerToIds[_owner].length` in `balanceOf`. This saves gas on two updates of `ownerToNFTokenCount` every time token is transferred and one when minted or burned.

This doesn't break compatibility with ERC721 spec, as you may leave `ERC721` and `ERC721Enumerable` as they are now.
This has drawback of slightly more expensive deploy and transfers for simpler `NFToken`, but is cheaper for full `NFTokenEnumerable` (+ `NFTokenMetadata`) and assuming OpenSea and others will require enumeration and developers will want to be listed there, this makes it cheaper in most cases. Also additional, non-standard funcitonality provided by `tokenOfOwnerByIndex` in basic `NFToken` might be a good thing.

**Comment by MoMannn** [comment] 2018-06-25 13:41
We know about this but it was a compromise since we wanted to make just the pure implementation of every extension and still do it with inheritance. The current implementation makes a gas sacrifice when implementing NFTokenEnumerable and your suggestion would make a sacrifice on NFToken but also the implementation would not be just plain ERC721. 

From optimization stand point the best solution would actually be to ditch inheritance and make 4 standalone implementations. That way both NFToken and NFTokenEnumerable would both be optimized and we would not need to make sacrifices anywhere. This is something we are considering more and more.

I guess this is as good of a place to start a discussion about this as any. 
@xpepermint @lknix @mg6maciej Thoughts?

**Comment by xpepermint** [comment] 2018-06-25 15:25
Solidity can kill you, confirmed :). You know what guys? I think having monolithic contracts with no inheritance, fully optimized for production might be the way to go.
This might sound ridiculous but just think about that. It's against everything I've learned in the past 20 years but it could be valid for solidity :).
Gas is important and it's our responsibility to make contracts as optimized as possible. I believe that making compromises here could be questionable. A nice modular code is probably not necessary in solidity because it's not a repetitive process like on the beck-end and front-end. Putting contracts to mainnet is a different story. It's real $ and every business wants that optimized.
Thoughts?

**Comment by mg6maciej** [comment] 2018-06-25 16:36
Thinking practically you don't even need anything other than monolithic `NFToken is ERC721, ERC721Enumerable, ERC721Metadata`. If my assumption above about OS and other platforms supporting NFTs is correct, most deployments will use the whole thing not to miss out on possible integrations in the future.
Sure, it might be possible someone will want to deploy subset, but it should be easier to modify the code for their purpose if it's single file contract than with `_mint`/`_burn` that call `addNFToken`/`removeNFToken` in the current form. Mainnet deployments should actually do exactly that: copy the code and remove `_burn` if it's not exposed via public method.

**Comment by MoMannn** [comment] 2018-06-25 17:56
Yeah but should not assume anything and if we make a monolithic implementation with all the extensions its pretty simple to make every component itself monolithic as well. So if we are going this route I would go all the way.. :)

**Comment by xpepermint** [comment] 2018-06-25 20:45
I think we all know what's following :).

**Comment by mg6maciej** [comment] 2018-06-25 20:53
Moar bugs after refactoring? ;)

**Comment by xpepermint** [comment] 2018-06-25 20:56
LOL :). We'll try the monolithic contracts, we'll check how we can test them, then we continue the discussion here.

**Comment by MoMannn** [comment] 2018-06-26 14:40
I have started working on monolithic contracts: https://github.com/MoMannn/ethereum-erc721/tree/mono (this is not part of the bounty). 
I still need a day of clean up, optimizations, additional tests and triple checks and then an internal audit.

But I have been doing some gas checks along the way and current results look promising: 

Contract | Method | Gas optimization %
------------ | ------------- | -------------
NFToken | transferFrom | 14%
NFToken | safeTransferFrom | 14%
NFToken | mint | 0.6% 
NFToken | burn | 1%
NFToken | approve | 1.5%
NFTokenMetadata  | mint | 0.88% 
NFTokenMetadata  | burn | 1%
NFTokenEnumerable  | mint | 13.3% 
NFTokenEnumerable  | burn | 6.6%
NFTokenEnumerable | transferFrom | 19.5%

**Comment by MoMannn** [comment] 2018-06-27 10:56
I did some more optimization and testing and have gotten even better results for burn and transfer for Enumerable. 

Here are test result from checking if it is the last user token and without for enumerable contract transferFrom:

Status | Gas consumption
------------ | -------------
Not checking if last token | 71114
Checking if last token -> transfer when we have multiple tokens | 71143 
Checking if last token -> transferring the last token we own | 66051 

So now it is all dependent on the usage of what is better. We need to make more then 174 transfers when owning multiple tokens for every 1 transaction owning only 1 token then no check is better other wise checking if last token is better. What do you guys think? Check of no check? @xpepermint @mg6maciej @lknix 


The same case is for burning tokens. 

While burning tokens we could also do a similar check if it is the last token of the contract not only if it is the last token of current owner but for that I think a version without checks is better since burning all token of the contract is much less likely event and even if you would do it you would probably need to burn quite a lot token before hand.

**Comment by mg6maciej** [comment] 2018-06-27 11:10
By "last token" do you mean a case when user has only one token or when transferred token has the largest index in user's array?
I think this optimization works for the latter case. If I have 5 tokens and transfer 3 of them out, there is increasing probability that optimization will be applied.
This optimization probably makes no sense for `tokens` array, because it will only apply to last minted token (unless some token is burned later).

**Comment by MoMannn** [comment] 2018-06-27 11:19
@mg6maciej By last token I meant that user has only one token. 

The case for transferring the token that has the largest index is next in my agenda.

**Comment by MoMannn** [comment] 2018-06-27 11:46
@mg6maciej Yes it is the latter case (well it applies to the fist case as well). I updated my comment above to better clarify and updated the gas consumption parameters since I did some more optimizations. 

From what I see I would agree with you on using the check. It still depends on use case but I think the check would be better for most.

**Comment by MoMannn** [comment] 2018-07-24 09:14
#127

**Closed by MoMannn** 2018-07-24 09:14 UTC
